CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    gmail VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS mhs_tb (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    nim VARCHAR(100) NOT NULL,
    jurusan VARCHAR(100) NOT NULL,
    ipk NUMERIC(10,2) NOT NULL,
    isActive BOOLEAN NOT NULL DEFAULT TRUE
);